### ISSUE TITLE
Move shortcuts

### ISSUE THREAD

**Issue by OpTi9** [Loac/obsidian-fight-note#1]
Awesome plugin! Will you add move shortcuts like: 
Quarter Circle Back: qcb
Half Circle Forward: hcf
Half Circle Back: hcb

so, for example, if i type `qcb` i will see:
![image](https://github.com/Loac/obsidian-fight-note/assets/55547016/e410f700-802a-48c2-8fe2-ab4bbb6d0d05)

**Comment by Loac** [comment]
Yeap, i will add it.

**Comment by Loac** [comment]
But this is not much shorter for writing than «d df b». Also, perhaps many will be «qcf» plate more convenient than the full notation with arrows. I also had an idea to replace the abbreviations with an icon, like this:
![](http://www.dustloop.com/wiki/images/thumb/e/e6/InputIcon_214.png/48px-InputIcon_214.png)

Need to think.

**Comment by Loac** [comment]
A couple of icon options.
<img width="335" alt="shortcut-1" src="https://github.com/Loac/obsidian-fight-note/assets/871128/f43bfee1-8ede-475f-a09a-38e93d58feda">
<img width="339" alt="shortcut-2" src="https://github.com/Loac/obsidian-fight-note/assets/871128/64c32f28-567d-41fd-92cb-b00c64586b1b">

**Comment by Loac** [comment]
Also extend tooltip.
<img width="292" alt="shortcut-3" src="https://github.com/Loac/obsidian-fight-note/assets/871128/0bf3b89a-b20f-41bf-bb80-188710a5f5b4">

**Comment by Loac** [comment]
Done.

**Comment by malagebidi** [comment]
> Awesome plugin! Will you add move shortcuts like: Quarter Circle Back: qcb Half Circle Forward: hcf Half Circle Back: hcb
> 
> so, for example, if i type `qcb` i will see: ![image](https://private-user-images.githubusercontent.com/55547016/313160114-e410f700-802a-48c2-8fe2-ab4bbb6d0d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTkxMzYsIm5iZiI6MTcxNDYxODgzNiwicGF0aCI6Ii81NTU0NzAxNi8zMTMxNjAxMTQtZTQxMGY3MDAtODAyYS00OGMyLThmZTItYWI0YmJiNmQwZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDAzMDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOGQ1ZmZjODE5MzczNjM3NDI2Njg4ZGFkOWY1OThiYjMzOWY1NTk1NmQwYWVkNTJhZDYyZGYzZTgxMGRiMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUFf30BR8IiRBwc4QlfkijrOyJeup5O_YkVrwkAZyyM)

KOF really need this.

**Comment by Loac** [comment]
it's has already done in 1.1.1 plugin version
